project:
  type: website
  output-dir: docs

website:
  title: "Timo Weckman"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: Publications
        file: publications.qmd
      - text: Blog posts
        file: blog_index.qmd
    right:
      - icon: github
        href: https://github.com/weckmantimo

format:
  html:
    theme: cosmo
    css: assets/css/custom.css
    include-before-body: _includes/header.html
    include-after-body: _includes/footer.html
